### ISSUE TITLE
Cannot decode cache: EOF

### ISSUE THREAD

**Issue by tyvdh** [computes/assets#1]
Starting today any time I try and run `./computes-daemon run` I'm getting a `Cannot decode cache: EOF` error.

**Comment by iamruinous** [comment]
There are a bunch of cache files stored in `~/.config/computes/queue-manager`. You could move them out of the way one at a time and see which one it is. Let me know which one  and I’ll dig into it.

**Comment by tyvdh** [comment]
Ahha! `gohocache.gob` is your culprit.

**Comment by iamruinous** [comment]
v14.1.2 should handle this better now

**Comment by tyvdh** [comment]
Haven't had the issue for awhile so closing for now. Thanks!
