### ISSUE TITLE
Daemon shutting down seemingly without reason

### ISSUE THREAD

**Issue by tyvdh** [computes/assets#2]
Disclaimer I'm running this on my Raspberry Pi

```bash
$ sudo ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub
Initializing daemon...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.15/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmPsJ2ouaWZ8nzsfNdFpQn5crbA4wszjtSG8kZaHWwDhYT
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.17.0.1/tcp/4001
Swarm announcing /ip4/192.168.0.15/tcp/4001
Swarm announcing /ip4/75.76.26.215/tcp/52790
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
```

It will stay up for a few seconds to a minute, and then shuts down seemingly without reason. I'm not actively pushing anything, it just dies.

Happy to provide any further helpful information.

**Comment by chrismatthieu** [comment]
IPFS can be memory hungry. I’ve run it fine on a RPi3 but not on RPi0. There is also a low-power mode parameter that you can use for smaller devices like RPis.

**Comment by tyvdh** [comment]
@chrismatthieu I've got the RPi3 B+

How do you enable the low-power mode?

**Comment by chrismatthieu** [comment]
https://github.com/ipfs/go-ipfs/blob/master/docs/config.md

**Comment by tyvdh** [comment]
So I ran `ipfs config profile apply lowpower` and it added `"lowpower": "apply"` to `~/.ipfs/config` but it's still shutting down.

**Comment by tyvdh** [comment]
Ran those commands and now I'm getting `Cannot decode cache: EOF` again. Cleared out the `~/.config/computes/queue-manager/` folder to no avail. I think I'm officially outside my comfort zone though.

Maybe some day you could publish a full RPi3 tutorial for getting some some the examples working with small local devices.

**Comment by chrismatthieu** [comment]
Sounds like progress. I believe @iamruinous is working on the caching issue.

**Comment by chrismatthieu** [comment]
BTW, I have a similar problem keeping IPFS alive on a low-memory digital ocean box. I ended up putting this bash script in a crontab that runs every minute - https://gist.github.com/chrismatthieu/b1373c044105a94b5fe84f1567ebe09b

**Comment by tyvdh** [comment]
Haven't run into the issue for awhile so closing for now
