### ISSUE TITLE
Error message:"Your build is too old! Update to the latest and try again"

### ISSUE THREAD

**Issue by RomaenZ** [computes/assets#6]
Although I am using the very latest version v14.1.7, I get the error message that my build is too old when I want to start the computes daemon.

**Comment by iamruinous** [comment]
Sorry about that! v14.1.8 is building right now, should be available in a few minutes.

**Comment by RomaenZ** [comment]
That is very good news. I have already checked almost all possible sources of errors that I could check myself and was not able to find anything.

Thanks for the quick response. Keep up the great work!

**Comment by iamruinous** [comment]
Here you go: https://github.com/computes/assets/releases/tag/v14.1.8
