### ISSUE TITLE
Licensing Timeout

### ISSUE THREAD

**Issue by RZett** [computes/assets#8]
Hi together,
I just wanted to report a problem that just came up. I can't start the Computes daemon right now, facing the following auth error notification:

> License Error Get https://licensing.computes.com/v14.1.8/: dial tcp 104.236.118.138:443: i/o timeout
> Unable to auth with https://licensing.computes.com/v14.1.8/: Get https://licensing.computes.com/v14.1.8/: dial tcp 104.236.118.138:443: i/o timeout

**Comment by iamruinous** [comment]
I'm not able to reproduce the issue. Can you try it again, or try from another network?

**Comment by RZett** [comment]
The third reboot of my Raspberry cluster seems to have repaired the routing. Looks like I have to deal with the stability of my cluster network again.

Thanks for the hint and sorry for the inconvenience.
