### ISSUE TITLE
computes-daemon thinks it's too old.

### ISSUE THREAD

**Issue by redaphid** [computes/assets#9]
I mean, I think I'm too old too, but it should be in denial like the rest of us.

env \
  COMPUTES_LICENSE_KEY=licence-key \
  COMPUTES_NAMESPACE=namespace \
  COMPUTES_QUEUE_SEED=example-queue \
  COMPUTES_WHITELIST=zdpuB3VESBQjvVmFaCcGWReNGeMzuMHErgmqpmAUAuQzMkjzR \
  computes-daemon run

 > Your build is too old! Update to the latest and try again

computes-daemon --version
 > computes-daemon version v14.1.8

**Comment by iamruinous** [comment]
Beta period is now closed. https://www.magicleap.com/stories/news/computes-joins-magic-leap
